version: "3.8"
services: 
  backend:
    container_name: todoapp_backend
    build: ./src/backend/
    depends_on:
      - "database"
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ConnectionStrings__TodoAppDbConnection=Host=database;Port=5432;Database=todoapp;Username=postgres;Password=postgres'
    command: ["./wait-for-it.sh", "database:5432", "--", "python", "app.py"]
  database:
    container_name: todoapp_database
    image: postgres:13
    volumes: 
      - ./.data-volume:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
